name = "cpq-api"
main = "src/index.js"
compatibility_date = "2024-01-09"
compatibility_flags = ["nodejs_compat"]
account_id = "34d894b7a693e5d10f6eb52820489854"  # Personal account

[vars]
REDIRECT_URI = "https://cpq-api.nav-sharma.workers.dev/auth/callback"

# Use these commands to set secrets:
# wrangler secret put SF_CLIENT_ID
# wrangler secret put SF_CLIENT_SECRET
